packages:
  - apps/*
  - packages/*
  - infrastructure/*

catalog:
  '@headlessui/react': ^2.1.0
  '@playwright/test': ^1.47.0
  '@testing-library/react': ^16.0.0
  '@types/node': ^20.16.13
  '@types/react': ^18.3.12
  '@types/react-dom': ^18.3.0
  '@typescript-eslint/eslint-plugin': ^7.0.0
  '@typescript-eslint/parser': ^7.0.0
  eslint: ^8.57.0
  next: ^14.0.0
  prettier: ^3.0.0
  react: ^18.3.0
  react-dom: ^18.3.0
  tailwindcss: ^3.4.0
  typescript: ^5.6.3
  vite: ^5.4.0
  vitest: ^2.0.0
  zustand: ^4.5.0

engines: {node: '>=20.0.0', pnpm: '>=8.0.0'}

hoist: true

resolution: {strategy: lowest-direct}

scripts:
  build: pnpm -r --filter='./apps/*' --filter='./packages/*' run build
  clean: pnpm -r --filter='./apps/*' --filter='./packages/*' run clean
  dev: echo 'Use make dev-deploy instead. No local processes allowed.'
  lint: pnpm -r --filter='./apps/*' --filter='./packages/*' run lint
  test: pnpm -r --filter='./apps/*' --filter='./packages/*' run test
  type-check: pnpm -r --filter='./apps/*' --filter='./packages/*' run type-check

shamefully-hoist: false

strict-peer-dependencies: true
