packages:
  - "apps/*"
  - "packages/*"
  - "infrastructure/*"

# Catalog configuration for shared dependencies
catalog:
  # Frontend dependencies
  react: ^18.3.0
  "react-dom": ^18.3.0
  next: ^14.0.0
  typescript: ^5.6.0
  "@types/react": ^18.3.0
  "@types/react-dom": ^18.3.0
  tailwindcss: ^3.4.0
  "@headlessui/react": ^2.1.0
  zustand: ^4.5.0
  vite: ^5.4.0
  vitest: ^2.0.0
  "@testing-library/react": ^16.0.0
  "@playwright/test": ^1.47.0

  # Development tools
  eslint: ^8.57.0
  "@typescript-eslint/eslint-plugin": ^7.0.0
  "@typescript-eslint/parser": ^7.0.0
  prettier: ^3.0.0
  "@types/node": ^20.0.0

# Node version requirement
engines:
  node: ">=20.0.0"
  pnpm: ">=8.0.0"

# Package resolution settings
resolution:
  strategy: "lowest-direct"

# Installation settings
hoist: true
shamefully-hoist: false
strict-peer-dependencies: true

# Scripts that can be run from root
scripts:
  dev: "echo 'Use make dev-deploy instead. No local processes allowed.'"
  build: "pnpm -r --filter='./apps/*' --filter='./packages/*' run build"
  test: "pnpm -r --filter='./apps/*' --filter='./packages/*' run test"
  lint: "pnpm -r --filter='./apps/*' --filter='./packages/*' run lint"
  type-check: "pnpm -r --filter='./apps/*' --filter='./packages/*' run type-check"
  clean: "pnpm -r --filter='./apps/*' --filter='./packages/*' run clean"