apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubechat.fullname" . }}
  labels:
    {{- include "kubechat.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kubechat.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kubechat.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kubechat.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.config.server.port }}
              protocol: TCP
          env:
            - name: LLM_PROVIDER
              value: {{ .Values.llm.provider | quote }}
            - name: LLM_FALLBACK
              value: {{ .Values.llm.enableFallback | quote }}
            {{- if .Values.llm.ollama.enabled }}
            - name: OLLAMA_URL
              {{- if .Values.llm.ollama.deploy }}
              value: "http://{{ include "kubechat.fullname" . }}-ollama:11434"
              {{- else }}
              value: {{ .Values.llm.ollama.url | quote }}
              {{- end }}
            - name: OLLAMA_MODEL
              value: {{ .Values.llm.ollama.model | quote }}
            {{- end }}
            {{- if .Values.llm.openai.enabled }}
            - name: OPENAI_MODEL
              value: {{ .Values.llm.openai.model | quote }}
            {{- if .Values.llm.openai.existingSecret }}
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.llm.openai.existingSecret }}
                  key: {{ .Values.llm.openai.secretKey }}
            {{- else if .Values.llm.openai.apiKey }}
            - name: OPENAI_API_KEY
              value: {{ .Values.llm.openai.apiKey | quote }}
            {{- end }}
            {{- end }}
            - name: DB_TYPE
              value: {{ .Values.config.database.type | quote }}
            {{- if .Values.config.database.url }}
            - name: DB_URL
              value: {{ .Values.config.database.url | quote }}
            {{- end }}
            - name: PORT
              value: {{ .Values.config.server.port | quote }}
            - name: HOST
              value: {{ .Values.config.server.host | quote }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: /data
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "kubechat.fullname" . }}-pvc
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}