{{- if and .Values.llm.ollama.enabled .Values.llm.ollama.deploy }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kubechat.fullname" . }}-ollama-init
  labels:
    {{- include "kubechat.labels" . | nindent 4 }}
    app.kubernetes.io/component: ollama-init
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      labels:
        {{- include "kubechat.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ollama-init
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-ollama
          image: busybox:1.35
          command: ['sh', '-c']
          args:
            - |
              echo "Waiting for Ollama service to be ready..."
              until nc -z {{ include "kubechat.fullname" . }}-ollama 11434; do
                echo "Waiting for Ollama..."
                sleep 5
              done
              echo "Ollama is ready!"
      containers:
        - name: pull-model
          image: curlimages/curl:latest
          command: ['sh', '-c']
          args:
            - |
              echo "Pulling Ollama model: {{ .Values.llm.ollama.model }}"
              
              # Wait a bit more to ensure Ollama is fully ready
              sleep 10
              
              # Pull the model
              curl -X POST http://{{ include "kubechat.fullname" . }}-ollama:11434/api/pull \
                -H "Content-Type: application/json" \
                -d '{"name": "{{ .Values.llm.ollama.model }}", "stream": false}'
              
              echo "Model pull completed!"
              
              # Verify model is available
              curl -s http://{{ include "kubechat.fullname" . }}-ollama:11434/api/tags
{{- end }}