{{- if and .Values.llm.ollama.enabled .Values.llm.ollama.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubechat.fullname" . }}-ollama
  labels:
    {{- include "kubechat.labels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
spec:
  type: ClusterIP
  ports:
    - port: 11434
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kubechat.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
{{- end }}