name: Bug Report
description: Report a bug to help us improve KubeChat
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for reporting a bug! 🐛

        Please fill out this template to help us understand and reproduce the issue.

        **⚠️ SECURITY NOTICE**: If this bug involves a security vulnerability, please do NOT create a public issue. Instead, report it privately via [security@kubechat.dev](mailto:security@kubechat.dev) or [GitHub Security Advisories](https://github.com/pramodksahoo/kubechat/security/advisories/new).

  - type: checkboxes
    id: security-check
    attributes:
      label: Security Checklist
      description: Please confirm this is not a security vulnerability
      options:
        - label: I confirm this is NOT a security vulnerability and is safe to report publicly
          required: true
        - label: I have checked existing issues to avoid duplicates
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Deploy KubeChat with '...'
        2. Navigate to '...'
        3. Enter query '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Please provide details about your environment
      value: |
        - **KubeChat Version**: [e.g., v1.0.0]
        - **Kubernetes Version**: [e.g., v1.28.0]
        - **Platform**: [e.g., EKS, GKE, AKS, local, Rancher Desktop]
        - **Helm Version**: [e.g., v3.15.0]
        - **AI Provider**: [e.g., Ollama, OpenAI]
        - **Browser** (if relevant): [e.g., Chrome 120, Safari 17]
        - **Operating System**: [e.g., macOS 14, Ubuntu 22.04]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: |
        Please include relevant logs (redact any sensitive information)
        ```
        kubectl logs -n kubechat deployment/kubechat-api
        kubectl logs -n kubechat deployment/kubechat-web
        ```
      placeholder: Paste logs here...
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, configuration files, etc.)
      placeholder: Additional information...

  - type: checkboxes
    id: troubleshooting
    attributes:
      label: Troubleshooting Checklist
      description: Please confirm you've tried basic troubleshooting
      options:
        - label: I have checked the documentation
        - label: I have searched existing issues
        - label: I have verified my Kubernetes cluster is healthy
        - label: I have checked KubeChat deployment status with `kubectl get pods -n kubechat`
        - label: I have reviewed application logs