name: Security Vulnerability (Private Report)
description: Report a security vulnerability privately
title: "[SECURITY]: "
labels: ["security", "critical"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ SECURITY VULNERABILITY REPORT

        **IMPORTANT**: This template is for private security reports only.

        ### Preferred Reporting Methods:
        1. **Email**: [security@kubechat.dev](mailto:security@kubechat.dev) (GPG key available on request)
        2. **GitHub Security Advisory**: [Private vulnerability reporting](https://github.com/pramodksahoo/kubechat/security/advisories/new)

        ### Please DO NOT:
        - Create public GitHub issues for security vulnerabilities
        - Share details in public forums or social media
        - Test the vulnerability against production systems you don't own

        ### What to Include:
        - Detailed description of the vulnerability
        - Steps to reproduce (in a safe environment)
        - Potential impact assessment
        - Suggested remediation (if known)
        - Your contact information for follow-up

        ### Our Commitment:
        - We will respond within 24 hours
        - We follow coordinated disclosure practices
        - We will credit you for responsible disclosure (if desired)

        ---

        **If you prefer not to use this public template, please use one of the preferred methods above.**

  - type: checkboxes
    id: confirmation
    attributes:
      label: Reporting Confirmation
      description: Please confirm you understand the process
      options:
        - label: I understand this is for security vulnerabilities only
          required: true
        - label: I have not disclosed this vulnerability publicly
          required: true
        - label: I will not exploit this vulnerability beyond necessary proof-of-concept
          required: true
        - label: I prefer private communication via email or GitHub Security Advisory
          required: false

  - type: textarea
    id: vulnerability-description
    attributes:
      label: Vulnerability Description
      description: Provide a clear description of the security issue
      placeholder: |
        - What is the vulnerability?
        - Which components are affected?
        - What type of security issue is this? (e.g., XSS, SQL injection, privilege escalation, etc.)
    validations:
      required: true

  - type: dropdown
    id: severity-assessment
    attributes:
      label: Severity Assessment (Your Assessment)
      description: How severe do you believe this vulnerability is?
      options:
        - Critical - Remote code execution, complete system compromise
        - High - Privilege escalation, significant data exposure
        - Medium - Limited information disclosure, denial of service
        - Low - Minor information disclosure, low impact
        - Informational - Security improvement suggestion
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      description: Detailed steps to reproduce the vulnerability (in a safe test environment)
      placeholder: |
        1. Set up test environment with...
        2. Configure KubeChat with...
        3. Perform action X...
        4. Observe security issue Y...

        **Note**: Please only test in environments you own or have explicit permission to test.
    validations:
      required: true

  - type: textarea
    id: impact-assessment
    attributes:
      label: Impact Assessment
      description: What could an attacker accomplish with this vulnerability?
      placeholder: |
        - What systems or data could be compromised?
        - What privileges could be gained?
        - What is the scope of potential damage?
        - Are there any mitigating factors?
    validations:
      required: true

  - type: textarea
    id: affected-versions
    attributes:
      label: Affected Versions
      description: Which versions of KubeChat are affected?
      placeholder: |
        - KubeChat version:
        - Kubernetes version:
        - Deployment configuration:
        - Browser (if web-related):
    validations:
      required: true

  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested Fix (Optional)
      description: If you have ideas for how to fix this vulnerability, please share them
      placeholder: |
        - Potential code changes
        - Configuration improvements
        - Architectural modifications

  - type: textarea
    id: proof-of-concept
    attributes:
      label: Proof of Concept (Optional)
      description: |
        If you have a safe proof-of-concept (no actual exploitation), you can include it here.
        **WARNING**: Do not include actual exploit code that could be misused.
      placeholder: |
        Safe demonstration code or detailed technical explanation...
      render: shell

  - type: input
    id: contact-info
    attributes:
      label: Contact Information
      description: How can we reach you for follow-up? (optional but recommended)
      placeholder: email@example.com or @githubusername

  - type: checkboxes
    id: disclosure-preferences
    attributes:
      label: Disclosure Preferences
      description: How would you like to be credited?
      options:
        - label: I would like to be credited for this discovery
        - label: I am willing to be contacted for clarification
        - label: I would like updates on the fix progress
        - label: I prefer to remain anonymous

  - type: markdown
    attributes:
      value: |
        ---

        ### Next Steps:
        1. Our security team will review this report within 24 hours
        2. We may contact you for additional information
        3. We will provide updates on our progress toward a fix
        4. We will coordinate with you on public disclosure timing

        **Thank you for helping keep KubeChat secure! 🔒**