# KubeChat Admin Credentials Secret
# Following: Built-in Admin Credential Management
# Enterprise-grade K8s Secret-based credential management with SOC 2/GDPR compliance

apiVersion: v1
kind: Secret
metadata:
  name: kubechat-admin-secret
  namespace: {{ .Values.global.namespace | default "kubechat" }}
  labels:
    app.kubernetes.io/name: {{ include "kubechat.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: admin-credentials
    app.kubernetes.io/part-of: kubechat
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    security.compliance/framework: "soc2-gdpr"
    security.classification: "confidential"
  annotations:
    helm.sh/resource-policy: keep
    security.rotation/policy: "90-days"
    security.audit/required: "true"
    security.encryption/at-rest: "aes-256"
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: Opaque
data:
  # Admin credentials with enterprise security standards
  admin_username: {{ "admin" | b64enc | quote }}
  # Generate secure random password (32 chars, enterprise complexity)
  admin_password: {{ randAlphaNum 32 | b64enc | quote }}
  admin_email: {{ "admin@kubechat.dev" | b64enc | quote }}
  # Metadata for credential management
  password_created: {{ now | unixEpoch | toString | b64enc | quote }}
  password_expires: {{ add (now | unixEpoch) 7776000 | toString | b64enc | quote }}
  last_rotation: {{ now | unixEpoch | toString | b64enc | quote }}
  rotation_count: {{ "0" | b64enc | quote }}
  # Security policy compliance
  min_password_length: {{ "24" | b64enc | quote }}
  max_password_age_days: {{ "90" | b64enc | quote }}
  password_complexity: {{ "enterprise" | b64enc | quote }}
  # Database sync configuration
  sync_enabled: {{ "true" | b64enc | quote }}
  last_db_sync: {{ now | unixEpoch | toString | b64enc | quote }}
  sync_status: {{ "pending_initial_sync" | b64enc | quote }}