{{- if .Values.backup.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kubechat.fullname" . }}-backup-storage
  namespace: {{ include "kubechat.namespace" . }}
  labels:
    {{- include "kubechat.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
{{- end }}