{{- if .Values.configMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubechat.fullname" . }}-config
  namespace: {{ include "kubechat.namespace" . }}
  labels:
    {{- include "kubechat.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    {{- with .Values.configMap.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  {{- with .Values.configMap.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  # Database connection configuration
  database_url: {{ include "kubechat.postgresql.connectionString" . | quote }}
  redis_url: {{ include "kubechat.redis.connectionString" . | quote }}
{{- end }}