{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name | default .Release.Namespace }}
  labels:
    {{- include "kubechat.labels" . | nindent 4 }}
    name: {{ .Values.namespace.name | default .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
{{- end }}