apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubechat.fullname" . }}-secret
  namespace: {{ include "kubechat.namespace" . }}
  labels:
    {{- include "kubechat.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ include "kubechat.namespace" . }}
    {{- with .Values.secret.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  # Database credentials
  {{- if .Values.postgresql.enabled }}
  db-username: {{ .Values.postgresql.auth.username | b64enc | quote }}
  {{- if .Values.postgresql.auth.password }}
  db-password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  {{- else }}
  db-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  {{- end }}

  # Redis credentials
  {{- if .Values.redis.enabled }}
  {{- if .Values.redis.auth.password }}
  redis-password: {{ .Values.redis.auth.password | b64enc | quote }}
  {{- else }}
  redis-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  {{- end }}

  # JWT secret for authentication
  {{- if .Values.jwtSecret }}
  jwt-secret: {{ .Values.jwtSecret | b64enc | quote }}
  {{- else }}
  jwt-secret: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}

  # Encryption key for sensitive data
  {{- if .Values.encryptionKey }}
  encryption-key: {{ .Values.encryptionKey | b64enc | quote }}
  {{- else }}
  encryption-key: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}

  # Additional secret data from values
  {{- with .Values.secret.data }}
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}