{{- if .Values.ollama.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubechat.fullname" . }}-ollama
  namespace: {{ include "kubechat.namespace" . }}
  labels:
    {{- include "kubechat.ollama.labels" . | nindent 4 }}
  {{- with .Values.ollama.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.ollama.service.type }}
  ports:
    - port: {{ .Values.ollama.service.port }}
      targetPort: {{ .Values.ollama.service.targetPort }}
      protocol: TCP
      name: http
      {{- if and (eq .Values.ollama.service.type "NodePort") .Values.ollama.service.nodePort }}
      nodePort: {{ .Values.ollama.service.nodePort }}
      {{- end }}
  selector:
    {{- include "kubechat.ollama.selectorLabels" . | nindent 4 }}
{{- end }}
