{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubechat.fullname" . }}-api
  namespace: {{ include "kubechat.namespace" . }}
  labels:
    {{- include "kubechat.api.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.api.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.api.service.type "NodePort") .Values.api.service.nodePort }}
      nodePort: {{ .Values.api.service.nodePort }}
      {{- end }}
  selector:
    {{- include "kubechat.api.selectorLabels" . | nindent 4 }}
{{- end }}