apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
spec:
  accessModes:
    - {{ .Values.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
{{- if .Values.pvc.storageClass }}
  storageClassName: {{ .Values.pvc.storageClass }}
{{- end }}
