{{ if not .Values.tls.secretName }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "helm-chart.default-tls-secret-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "helm-chart.default-tls-secret-name" . }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
data:
{{ ( include "helm-chart.gen-certs" . ) | indent 2 }}
{{ end }}